<?php
/**
 * @file
 * Ding Search Collection.
 */

/**
 * Implements hook_entity_view().
 */
function ding_search_collection_entity_view($entity, $entity_type, $view_mode, $langcode) {
  // Apply only to ting_collection teaser.
  if ($entity_type != 'ting_collection' && $view_mode != 'teaser') {
    return;
  }
  // Do not show on collection page.
  if (arg(0) == 'ting' && arg(1) == 'collection') {
    return;
  }
  // If for some reason there is no 'entities' property.
  if (!isset($entity->entities)) {
    return;
  }
  // Do not show for collections that have 1 item.
  if (count($entity->entities) == 1) {
    return;
  }

  $entity->content['#post_render'] = array('ding_search_collection_render');
  drupal_add_css(
    drupal_get_path('module', 'ding_search_collection') . '/ding_search_collection.css'
  );
}

/**
 * Implements hook_theme_registry_alter().
 */
function ding_search_collection_theme_registry_alter(&$theme_registry) {
  if (!empty($theme_registry['search_result'])) {
    $theme_registry['search_result']['process functions'][] = 'ding_search_collection_search_result';
  }
}

/**
 * Template preprocess callback.
 */
function ding_search_collection_search_result(&$variables) {
  // Check if result has collection divs.
  if (strpos($variables['snippet'], 'collection-bg-1')) {
    $variables['classes'] .= ' ding-search-collection';
  }
}

/**
 * Post render callback.
 *
 * Adds collection visuals to search result.
 */
function ding_search_collection_render($children, $elements) {
  return '<div class="collection-bg-2"></div>'
    . '<div class="collection-bg-1"></div>'
    . '<div class="ting-collection-wrapper">' . $children . '</div>';
}
